// Persistent neutral settlements with separate people, stores and a small local economy.
(() => {
  'use strict';
  const RULES=Object.freeze({version:1,mealEveryDays:30,foodPerPerson:1,productionEveryDays:10});
  const FACTIONS=[
    {owner:1,id:'clan-guado',name:'Clan del Guado',goods:{food:24,grain:18,forage:12},money:220},
    {owner:2,id:'lega-colline',name:'Lega delle Colline',goods:{food:18,barley:20,stone:12},money:260}
  ];
  window.TERRA_NEUTRALS={rules:RULES,factions:FACTIONS};
  const alivePeople=(game,owner)=>game.units.filter(u=>u.owner===owner&&u.health>0);
  const owned=(entity,owner)=>entity&&entity.owner===owner&&entity.alive;
  Game.prototype.neutralSettlement=function(owner){const base=this.buildings.find(b=>b.owner===owner&&b.type==='base'&&b.alive);if(!base)return null;return{owner,id:base.settlementId,name:base.factionName,base,market:this.buildings.find(b=>b.owner===owner&&b.type==='market'&&b.alive),people:alivePeople(this,owner)};};
  Game.prototype.findNeutralSite=function(px,py){for(let r=0;r<18;r++)for(let i=0;i<32;i++){const x=Math.max(3,Math.min(WORLD_SIZE-4,Math.floor(px+Math.cos(i/32*Math.PI*2)*r))),y=Math.max(3,Math.min(WORLD_SIZE-4,Math.floor(py+Math.sin(i/32*Math.PI*2)*r))),tile=this.world.tile(x,y);if(tile&&BIOME[tile.biome].walk&&!this.buildings.some(b=>dist(b,{x:x+.5,y:y+.5})<5))return{x,y};}return{x:WORLD_SIZE-8,y:8};};
  Game.prototype.createNeutralSettlements=function(){if(this.buildings.some(b=>b.owner>0&&b.settlementId))return;for(const[index,f]of FACTIONS.entries()){const site=this.findNeutralSite(index?WORLD_SIZE-14:14,index?WORLD_SIZE-18:16),base=new Building('base',site.x,site.y,f.owner,true),house=new Building('house',site.x+2,site.y,f.owner,true),market=new Building('market',site.x,site.y+2,f.owner,true);for(const b of[base,house,market]){b.settlementId=f.id;b.factionName=f.name;this.buildings.push(b);}this.ensureInventories();base.inventory.items={...f.goods};market.inventory.items={};market.money=f.money;for(let n=0;n<3;n++){const u=new Unit(NAMES[(f.owner*4+n)%NAMES.length],house.x,house.y,this.rng);u.owner=f.owner;u.neutralSettlementId=f.id;if(n<2){u.location={kind:'resident',settlementId:house.id};house.residents.push(u.id);}else{u.x=site.x+1.5;u.y=site.y+1.5;}this.units.push(u);}}this.ensureMarkets();};
  Game.prototype.neutralEconomyDay=function(){this.ensureInventories();this.ensureMarkets();for(const f of FACTIONS){const s=this.neutralSettlement(f.owner);if(!s)continue;const population=s.people.length,items=s.base.inventory.items;if(this.totalDays%RULES.productionEveryDays===0&&population){const good=f.owner===1?'grain':'barley';items[good]=(items[good]||0)+population;items.forage=(items.forage||0)+Math.max(1,Math.floor(population/2));}if(this.totalDays%RULES.mealEveryDays===0&&population){let remaining=population*RULES.foodPerPerson;for(const good of['bread','barleyBread','food']){const used=Math.min(remaining,items[good]||0);items[good]=(items[good]||0)-used;remaining-=used;}s.base.foodShortage=remaining;}if(s.market){const food=(items.food||0)+(items.bread||0)+(items.barleyBread||0),coverage=population?food/population:0;s.market.demand.food=Math.max(.5,Math.min(3,1.8-coverage/10+(s.base.foodShortage||0)*.2));s.market.demand.grain=Math.max(.5,Math.min(3,1.4-(items.grain||0)/30));s.market.demand.barley=Math.max(.5,Math.min(3,1.4-(items.barley||0)/30));}}};
  const newGame=Game.prototype.newGame;Game.prototype.newGame=function(seed){newGame.call(this,seed);if(window.__ENABLE_NEUTRALS__!==false)this.createNeutralSettlements();};
  const advanceDay=Game.prototype.advanceDay;Game.prototype.advanceDay=function(){advanceDay.call(this);this.neutralEconomyDay();};
  const assignHaul=Game.prototype.assignHaul;Game.prototype.assignHaul=function(u,source,destination,good,repeat=true){if(!u||!owned(source,u.owner)||!owned(destination,u.owner))return'Accesso negato: persone e depositi devono appartenere allo stesso insediamento.';return assignHaul.call(this,u,source,destination,good,repeat);};
  const assignProduction=Game.prototype.assignProduction;Game.prototype.assignProduction=function(u,b){if(!u||!owned(b,u.owner))return'Accesso negato: la fabbrica appartiene a un altro insediamento.';return assignProduction.call(this,u,b);};
  Game.prototype.nearestStorage=function(u){const candidates=this.buildings.filter(b=>owned(b,u.owner)&&b.built&&['base','warehouse'].includes(b.type)&&this.freeSpace(b)>0).sort((a,b)=>dist(u,a)-dist(u,b));return candidates.find(b=>this.pathToBuilding(u,b)!==null)||null;};
  const selectionHTML=Game.prototype.selectionHTML;Game.prototype.selectionHTML=function(e){let html=selectionHTML.call(this,e);if(e instanceof Building&&e.owner>0&&e.settlementId){const s=this.neutralSettlement(e.owner);html+=`<p><b>${e.factionName}</b> · popolazione ${s?.people.length||0} · scorte e proprietà separate.</p>`;}return html;};
})();
