// Political state is attached to each persistent neutral settlement, never to copied people or goods.
(() => {
  'use strict';
  const RULES=Object.freeze({version:1,giftFood:5,giftInfluence:12,giftLoyalty:4,intimidateInfluence:5,intimidateResistance:12,alliedInfluence:75,alliedLoyalty:60,hostileResistance:75,hostileLoyalty:20});
  window.TERRA_POLITICS=RULES;
  const bounded=n=>Math.max(0,Math.min(100,Math.round(n)));
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  Game.prototype.ensurePolitics=function(){for(const f of TERRA_NEUTRALS.factions){const s=this.neutralSettlement(f.owner);if(!s)continue;const b=s.base;if(!Number.isFinite(b.loyalty))b.loyalty=50;if(!Number.isFinite(b.resistance))b.resistance=45;if(!Number.isFinite(b.playerInfluence))b.playerInfluence=0;if(!Array.isArray(b.diplomacyLedger))b.diplomacyLedger=[];b.loyalty=bounded(b.loyalty);b.resistance=bounded(b.resistance);b.playerInfluence=bounded(b.playerInfluence);b.relationship=this.politicalRelationship(b);}};
  Game.prototype.politicalRelationship=function(base){if(base.resistance>=RULES.hostileResistance||base.loyalty<=RULES.hostileLoyalty)return'hostile';if(base.playerInfluence>=RULES.alliedInfluence&&base.loyalty>=RULES.alliedLoyalty&&base.resistance<50)return'allied';if(base.playerInfluence>=30)return'friendly';return'neutral';};
  Game.prototype.diplomacyAction=function(owner,kind,transactionId){this.ensurePolitics();const s=this.neutralSettlement(owner),own=this.buildings.find(b=>b.owner===0&&b.type==='base'&&b.alive&&b.built);if(!s||!own||!['gift','intimidate'].includes(kind)||typeof transactionId!=='string')return{ok:false,error:'Azione diplomatica non valida.'};const old=s.base.diplomacyLedger.find(x=>x.id===transactionId);if(old)return{...old,replayed:true};if(kind==='gift'){if(this.available(own,'food')<RULES.giftFood)return{ok:false,error:`Servono ${RULES.giftFood} cibo libero alla Casa comune.`};own.inventory.items.food-=RULES.giftFood;s.base.playerInfluence=bounded(s.base.playerInfluence+RULES.giftInfluence);s.base.loyalty=bounded(s.base.loyalty+RULES.giftLoyalty);s.base.resistance=bounded(s.base.resistance-3);}else{s.base.playerInfluence=bounded(s.base.playerInfluence+RULES.intimidateInfluence);s.base.loyalty=bounded(s.base.loyalty-5);s.base.resistance=bounded(s.base.resistance+RULES.intimidateResistance);}s.base.relationship=this.politicalRelationship(s.base);const result={id:transactionId,ok:true,kind,owner,relationship:s.base.relationship};s.base.diplomacyLedger.push(result);if(s.base.diplomacyLedger.length>40)s.base.diplomacyLedger.splice(0,s.base.diplomacyLedger.length-40);return result;};
  const neutralDay=Game.prototype.neutralEconomyDay;Game.prototype.neutralEconomyDay=function(){neutralDay.call(this);this.ensurePolitics();if(this.totalDays%TERRA_NEUTRALS.rules.mealEveryDays!==0)return;for(const f of TERRA_NEUTRALS.factions){const s=this.neutralSettlement(f.owner);if(!s)continue;if(s.base.foodShortage>0){s.base.loyalty=bounded(s.base.loyalty-3);s.base.resistance=bounded(s.base.resistance+5);}else{s.base.loyalty=bounded(s.base.loyalty+1);s.base.resistance=bounded(s.base.resistance-1);}s.base.relationship=this.politicalRelationship(s.base);}};
  const marketPrice=Game.prototype.marketPrice;Game.prototype.marketPrice=function(market,good,side='buy'){const price=marketPrice.call(this,market,good,side);if(price===null||market.owner===0)return price;this.ensurePolitics();const rel=this.neutralSettlement(market.owner)?.base.relationship;if(rel==='allied')return Math.max(1,Math.round(price*(side==='buy'?.85:1.12)));if(rel==='friendly')return Math.max(1,Math.round(price*(side==='buy'?.93:1.06)));return price;};
  const trade=Game.prototype.tradeAtMarket;Game.prototype.tradeAtMarket=function(args){if(args.market?.owner>0){this.ensurePolitics();if(this.neutralSettlement(args.market.owner)?.base.relationship==='hostile')return{ok:false,error:'Rapporti ostili: il mercato rifiuta lo scambio.'};}return trade.call(this,args);};
  Game.prototype.renderPolitics=function(){this.ensurePolitics();const label={neutral:'Neutrale',friendly:'Amichevole',allied:'Alleato',hostile:'Ostile'};$('#politicsList').innerHTML=TERRA_NEUTRALS.factions.map(f=>{const s=this.neutralSettlement(f.owner);if(!s)return'';const b=s.base;return`<article><h3>${escape(s.name)} · ${label[b.relationship]}</h3><p>Lealtà ${b.loyalty}/100 · Resistenza ${b.resistance}/100 · Influenza ${b.playerInfluence}/100</p><button type="button" data-politics="gift" data-owner="${f.owner}">Dona ${RULES.giftFood} cibo</button><button type="button" data-politics="intimidate" data-owner="${f.owner}">Fai pressione</button></article>`;}).join('');$('#politicsRules').textContent='Parametri provvisori: influenza 30 rende amichevoli; influenza 75 e lealtà 60 consentono alleanza; resistenza 75 o lealtà 20 causano ostilità.';$('#politicsList').querySelectorAll('[data-politics]').forEach(button=>button.onclick=()=>{const id=crypto.randomUUID?.()||`dip-${Date.now()}`,r=this.diplomacyAction(Number(button.dataset.owner),button.dataset.politics,id);$('#politicsStatus').textContent=r.ok?(r.replayed?'Azione già registrata.':`Relazione aggiornata: ${label[r.relationship]}.`):r.error;if(r.ok)this.save(true);this.renderPolitics();});};
  const initUI=Game.prototype.initUI;Game.prototype.initUI=function(){initUI.call(this);const d=$('#politicsDialog');$('#politicsBtn').onclick=()=>{this.pauseBeforePolitics=this.paused;this.setPaused(true);this.pointerCancel();$('#politicsStatus').textContent='';this.renderPolitics();d.showModal();};$('#closePolitics').onclick=()=>d.close();d.addEventListener('close',()=>{if(!this.suspended&&!this.backgroundDuringPolitics)this.setPaused(this.pauseBeforePolitics);this.backgroundDuringPolitics=false;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&d.open)this.backgroundDuringPolitics=true;});};
  const snapshot=Game.prototype.snapshot;Game.prototype.snapshot=function(){this.ensurePolitics();const d=snapshot.call(this);d.politicsRules=1;return d;};
  const load=Game.prototype.load;Game.prototype.load=function(){const ok=load.call(this);if(ok)this.ensurePolitics();return ok;};
  const selectionHTML=Game.prototype.selectionHTML;Game.prototype.selectionHTML=function(e){let html=selectionHTML.call(this,e);if(e instanceof Building&&e.owner>0&&e.settlementId){this.ensurePolitics();const b=this.neutralSettlement(e.owner).base;html+=`<p>Relazione: <b>${b.relationship}</b> · lealtà ${b.loyalty} · resistenza ${b.resistance} · influenza ${b.playerInfluence}.</p>`;}return html;};
})();
