const assert=require('node:assert/strict');
const make=require('./harness.cjs');
function setup(){const e=make(),g=e.g;g.newGame(79);g.world.resources=[];g.animals=[];g.raiders=[];g.warCamps=[];g.world.collisionCamps=[];for(const t of g.world.tiles){t.biome='grass';t.z=0;}for(const u of g.units){g.cancelTask(u);u.x=10.5;u.y=10.5;}const farm=e.run("(()=>{const b=new Building('farm',40,40,0,true);game.buildings.push(b);game.ensureInventories();return b;})()");return {...e,farm};}
let n=0;function test(label,fn){fn();console.log('PASS',label);n++;}
test('only fields permit both human and animal traversal; spawn remains clear',()=>{const e=setup(),{g,farm}=e;assert(g.world.walkable(40,40,1,null,g.buildings));assert(g.animalTerrainClear(farm));assert(!g.spawnPositionFree(farm));assert.equal(g.buildingDistance(farm,farm),0);assert(g.movementClear({x:39.5,y:40.5},{x:41.5,y:40.5}));for(const type of ['base','warehouse','house','pen','market','sawmill','mill','bakery','palisade','tower']){farm.type=type;assert(!g.world.walkable(40,40,1,null,g.buildings),type);assert(!g.animalTerrainClear(farm),type);}});
test('all four footprints, staffing and guide match handoff',()=>{const {g,farm,sandbox}=setup();for(const [id,c] of Object.entries(sandbox.TERRA_CROPS)){assert(g.setCrop(farm,id));const b=sandbox.VER_SACRUM_VILLAGE.bounds(farm);assert.equal(b.right-b.left,c.side);assert.equal(c.maxWorkers,c.side===1?2:8);assert.equal(g.nearestAt(g.buildings,{x:b.right-.1,y:b.bottom-.1},.1),farm);assert(g.selectionHTML(farm).includes('Guida alle quattro colture'));}});
test('expansion fails atomically for structures, resources, actors and water',()=>{for(const kind of ['structure','resource','actor','water']){const e=setup(),{g,farm}=e;if(kind==='structure')e.run("game.buildings.push(new Building('pen',41,41,0,true))");if(kind==='resource')g.world.resources.push({x:41.5,y:41.5,amount:10});if(kind==='actor'){g.units[0].x=41.5;g.units[0].y=41.5;}if(kind==='water')g.world.tile(41,41).biome='sea';assert.equal(g.setCrop(farm,'olives'),false,kind);assert.equal(farm.crop,'grain');}});
test('staff cap reserves travelling workers and preserves rejected worker order',()=>{const e=setup(),{g,farm}=e;while(g.units.length<9)e.run("game.units.push(new Unit('Contadino',38.5,40.5,game.rng))");for(const u of g.units){u.location={kind:'world'};u.owner=0;u.x=38.5;u.y=40.5;}assert(g.assignFarm(g.units[0],farm));assert(g.assignFarm(g.units[1],farm));const third=g.units[2];const previous=third.task;assert.equal(g.assignFarm(third,farm),false);assert.equal(third.task,previous);assert(g.setCrop(farm,'grapes'));for(let i=2;i<8;i++)assert(g.assignFarm(g.units[i],farm));assert.equal(g.assignFarm(g.units[8],farm),false);assert.equal(g.setCrop(farm,'grain'),false);assert.equal(farm.crop,'grapes');});
test('crop footprint and inventory survive load without overlapping buildings',()=>{const {g,farm,sandbox}=setup();assert(g.setCrop(farm,'olives'));farm.inventory.items.olives=37;assert(g.save());assert(g.load());const b=g.buildings.find(b=>b.id===farm.id);assert.equal(b.crop,'olives');assert.equal(b.inventory.items.olives,37);const r=sandbox.VER_SACRUM_VILLAGE.bounds(b);assert.equal(r.right-r.left,2);assert(g.world.walkable(Math.floor(b.x)+1,Math.floor(b.y)+1,1,null,g.buildings));});
console.log(`${n} mobile agriculture regressions passed.`);
