const {test}=require('node:test'),assert=require('node:assert/strict'),make=require('./harness.cjs');
const ev=(pointerId,x,y)=>({pointerId,clientX:x,clientY:y,preventDefault(){},stopPropagation(){}});
function setup(){const e=make(),g=e.g;for(const t of g.world.tiles){t.biome='grass';t.z=0;}g.screenToWorld=(x,y)=>({x:x*30,y:y*30});g.buildMode='warehouse';return e;}
test('hold and drag preview without spending or panning; release places at final tile once',()=>{const {g}=setup(),n=g.buildings.length,stock=JSON.stringify(g.communalStock()),camera={...g.camera};g.pointerDown(ev(1,60,60));assert(g.buildPreview.valid);assert.equal(g.buildings.length,n);assert.equal(JSON.stringify(g.communalStock()),stock);g.pointerMove(ev(1,72,60));assert.equal(g.buildPreview.x,72);assert.deepEqual({...g.camera},camera);g.pointerUp(ev(1,72,60));assert.equal(g.buildings.length,n+1);assert.equal(Math.floor(g.buildings.at(-1).x),72);assert.equal(g.buildPreview,null);g.pointerUp(ev(1,72,60));assert.equal(g.buildings.length,n+1);assert.equal(g.buildMode,'warehouse');});
test('MOD tap cancels the building tool and preserves units, stock and buildings',()=>{const {g,byId}=setup(),selected=g.selected,n=g.buildings.length,stock=JSON.stringify(g.communalStock());byId.touchModifier.listeners.pointerdown[0](ev(99,0,0));g.pointerDown(ev(1,60,60));assert.equal(g.buildMode,null);assert.equal(g.buildPreview,null);byId.touchModifier.listeners.pointerup[0](ev(99,0,0));g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n);assert.equal(JSON.stringify(g.communalStock()),stock);assert.equal(g.selected,selected);});
test('MOD pressed during an active preview cancels instead of placing',()=>{const {g,byId}=setup(),n=g.buildings.length;g.pointerDown(ev(1,60,60));byId.touchModifier.listeners.pointerdown[0](ev(99,0,0));g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n);assert.equal(g.buildMode,null);});
test('invalid terrain, occupied footprint and out-of-canvas release create no building',()=>{for(const reason of ['terrain','occupied','outside']){const {g}=setup(),n=g.buildings.length;let x=60,y=60;if(reason==='terrain')g.world.tile(60,60).biome='sea';if(reason==='occupied'){const b=g.buildings[0];x=Math.floor(b.x);y=Math.floor(b.y);}g.pointerDown(ev(1,x,y));if(reason!=='outside')assert.equal(g.buildPreview.valid,false);g.pointerUp(ev(1,reason==='outside'?-10:x,y));assert.equal(g.buildings.length,n);}});
test('pinch and pointer cancellation discard preview and never place on leftover release',()=>{for(const pinch of [true,false]){const {g}=setup(),n=g.buildings.length;g.pointerDown(ev(1,60,60));if(pinch){g.pointerDown(ev(2,80,80));g.pointerMove(ev(2,90,90));g.pointerUp(ev(2,90,90));}else g.pointerCancel();g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n);assert.equal(g.buildPreview,null);}});
test('village preview uses four-tile footprint and clears on tool change',()=>{const {g,sandbox}=setup();g.buildMode='house';g.pointerDown(ev(1,60,60));const r=sandbox.VER_SACRUM_VILLAGE.bounds(g.buildPreview.ghost);assert.equal(r.right-r.left,4);g.buildMode='farm';const n=g.buildings.length;g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n);assert.equal(g.buildPreview,null);});
test('release rechecks resource availability instead of trusting old green preview',()=>{const {g}=setup();g.pointerDown(ev(1,60,60));assert(g.buildPreview.valid);for(const b of g.communalStores())b.inventory.items.wood=0;const n=g.buildings.length;g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n);});
test('ordinary quick tap still places a building exactly once',()=>{const {g}=setup(),n=g.buildings.length;g.pointerDown(ev(1,60,60));g.pointerUp(ev(1,60,60));assert.equal(g.buildings.length,n+1);});
