const assert=require('node:assert/strict');const make=require('./harness.cjs');let count=0;
function test(name,fn){fn();console.log('PASS',name);count++;}
function setup(){const e=make();e.g.newGame(321);return e;}
test('dedicated dialog opens selected person, pauses and exposes identity, slots, stats',()=>{const e=setup(),u=e.g.units[0];e.g.selected=u;e.byId.characterBtn.onclick();assert(e.byId.characterDialog.open);assert(e.g.paused);assert.equal(e.g.characterPersonId,u.id);assert.match(e.byId.characterId.textContent,new RegExp(u.id));assert.match(e.byId['gear-body'].textContent,/Tunica/);assert.match(e.byId.characterStats.textContent,/Salute/);assert(!e.byId.characterStats.textContent.includes('abilità'));});
test('selection changes cannot redirect an open character transfer',()=>{const e=setup(),a=e.g.units[0],b=e.g.units[1];e.g.openCharacter(a.id);const id=e.g.personEquipment(a.id).slots.body.id;e.g.selected=b;e.byId.characterRemove.onclick();assert.equal(e.g.gear.find(i=>i.id===id).location.holder,a.id);assert.equal(e.g.gear.find(i=>i.id===id).location.kind,'bag');assert(e.g.personEquipment(b.id).slots.body);});
test('explicit person picker changes identity without moving any items',()=>{const e=setup(),a=e.g.units[0],b=e.g.units[1];e.g.openCharacter(a.id);const before=JSON.stringify(e.g.gear);e.byId.characterPeople.value=b.id;e.byId.characterPeople.onchange();assert.equal(e.g.characterPersonId,b.id);assert.equal(JSON.stringify(e.g.gear),before);});
test('remove/equip UI round trip persists, closing owns no data',()=>{const e=setup(),u=e.g.units[0];e.g.openCharacter(u.id);const id=e.g.personEquipment(u.id).slots.body.id;e.byId.characterRemove.onclick();e.byId.characterEquip.onclick();e.byId.closeCharacter.onclick();assert.equal(e.g.paused,false);assert.equal(e.g.characterPersonId,null);assert(e.g.load());assert.equal(e.g.personEquipment(u.id).slots.body.id,id);});
test('resident can be inspected without exiting or creating a world copy',()=>{const e=setup(),u=e.g.units[0],b=e.run("(()=>{const b=new Building('house',45,45,0,true);game.buildings.push(b);return b})()");e.g.enterResident(u,b);assert(e.g.openCharacter(u.id));assert.match(e.byId.characterIdentity.textContent,/Residente/);e.byId.characterRemove.onclick();assert.equal(u.location.kind,'resident');assert.equal(e.g.units.filter(p=>p.id===u.id).length,1);});
test('background and preexisting pause survive closing',()=>{const e=setup();e.g.setPaused(true);e.g.openCharacter(e.g.units[0].id);e.byId.closeCharacter.onclick();assert(e.g.paused);e.g.setPaused(false);e.g.openCharacter(e.g.units[0].id);e.g.suspend();e.g.resumeFromBackground();e.byId.closeCharacter.onclick();assert(e.g.paused);});
test('invalid person rejects dialog and stale item command cannot affect another owner',()=>{const e=setup(),u=e.g.units[0];assert.equal(e.g.openCharacter('absent'),false);e.g.openCharacter(u.id);const i=e.g.personEquipment(u.id).slots.body;e.g.transferEquipment(u.id,i.id,{...i.location},{kind:'bag',holder:u.id});e.byId.characterEquip.onclick();assert.match(e.byId.characterStatus.textContent,/già spostato/);assert.equal(i.location.kind,'bag');});
test('failed persistence is visible while live ownership remains unique',()=>{const e=setup();e.g.openCharacter(e.g.units[0].id);e.sandbox.localStorage.setItem=()=>{throw new Error('quota')};e.byId.characterRemove.onclick();assert.match(e.byId.characterStatus.textContent,/Salvataggio non riuscito/);assert.equal(new Set(e.g.gear.map(i=>i.id)).size,e.g.gear.length);});
console.log(`${count} character regressions passed.`);
