const assert=require('node:assert/strict');
const make=require('./harness.cjs');
const SLOT='terra-italica-save-v5';
function setup(){const e=make(),g=e.g;g.newGame(212);g.paused=false;g.raiders=[];for(const t of g.world.tiles){t.biome='grass';t.z=0;t.nearWater=false;}const farm=e.run("(()=>{const b=new Building('farm',40,40,0,true);game.buildings.push(b);game.ensureInventories();return b})()"),u=g.units[0];u.x=farm.x+1;u.y=farm.y;u.stance='passive';g.assignFarm(u,farm);u.state='farming';return{...e,g,farm,u};}
let count=0;function test(name,fn){fn();count++;console.log('PASS',name)}
test('four configurable crops expose distinct goods, base days and yields',()=>{const {sandbox}=setup(),c=sandbox.TERRA_CROPS;assert.deepEqual(Object.keys(c),['grain','barley','grapes','olives']);assert.deepEqual(Object.values(c).map(x=>x.days),[10,10,30,40]);assert.deepEqual(Object.values(c).map(x=>x.yield),[20,20,80,100]);});
test('every crop harvest remains in the field inventory',()=>{for(const id of ['grain','barley','grapes','olives']){const {g,farm,u}=setup();farm.crop=id;farm.growth=1;g.buildingDay(farm);assert((farm.inventory.items[id]||0)>0,id);assert.equal(u.inventory.amount,0);assert.equal(g.stock[id]||0,0);}});
test('full field retains complete ready harvest without loss or partial credit',()=>{const {g,farm}=setup();farm.crop='olives';farm.growth=1;farm.inventory.items.wood=farm.inventory.capacity;g.buildingDay(farm);assert.equal(farm.growth,1);assert.equal(farm.inventory.items.olives||0,0);assert.equal(g.stock.olives||0,0);});
test('terrain, water and crop season change growth and yield',()=>{const dry=setup(),wet=setup();dry.farm.crop=wet.farm.crop='grapes';dry.g.month=0;wet.g.month=6;wet.g.world.tile(Math.floor(wet.farm.x),Math.floor(wet.farm.y)).nearWater=true;dry.g.buildingDay(dry.farm);wet.g.buildingDay(wet.farm);assert(wet.farm.growth>dry.farm.growth);dry.farm.growth=wet.farm.growth=1;dry.g.buildingDay(dry.farm);wet.g.buildingDay(wet.farm);assert(wet.farm.inventory.items.grapes>dry.farm.inventory.items.grapes);});
test('crop cannot change mid-cycle but can change between cycles',()=>{const {g,farm}=setup();farm.growth=.2;assert.equal(g.setCrop(farm,'olives'),false);assert.equal(farm.crop,'grain');farm.growth=0;assert.equal(g.setCrop(farm,'olives'),true);assert.equal(farm.crop,'olives');});
test('crop and local harvest survive save and reload',()=>{const {g,farm}=setup();farm.crop='barley';farm.growth=1;g.buildingDay(farm);const amount=farm.inventory.items.barley,id=farm.id;assert(g.save());assert(g.load());const loaded=g.buildings.find(b=>b.id===id);assert.equal(loaded.crop,'barley');assert.equal(loaded.inventory.items.barley,amount);});
test('legacy v5 Grano field migrates conservatively to grain',()=>{const {g,storage,farm}=setup(),d=g.snapshot();d.buildings.find(b=>b.id===farm.id).crop='Grano';storage.set(SLOT,JSON.stringify(d));assert(g.load());assert.equal(g.buildings.find(b=>b.id===farm.id).crop,'grain');});
console.log(`${count} crop and season regressions passed.`);
