const assert=require('node:assert/strict');
const make=require('./harness.cjs');let count=0;
function test(name,fn){fn();console.log('PASS',name);count++;}
function setup(){const e=make();e.g.newGame(321);e.u=e.g.units[0];e.item=e.g.personEquipment(e.u.id).slots.body;return e;}
function move(e,kind,holder=e.u.id,slot){return e.g.transferEquipment(e.u.id,e.item.id,{...e.item.location},{kind,holder,slot});}
test('one object per initial person; bag and bulk cargo do not alias',()=>{const e=setup();assert.equal(e.g.gear.length,5);const cargo=JSON.stringify(e.u.inventory),stock=JSON.stringify(e.g.stock);assert.equal(move(e,'bag'),null);assert.equal(e.g.personEquipment(e.u.id).bag.length,1);assert.equal(e.g.personEquipment(e.u.id).slots.body,null);assert.equal(JSON.stringify(e.u.inventory),cargo);assert.equal(JSON.stringify(e.g.stock),stock);});
test('equip/remove/reload preserves unique ID and rejects duplicate command',()=>{const e=setup(),old={...e.item.location},id=e.item.id;assert.equal(move(e,'bag'),null);assert.match(e.g.transferEquipment(e.u.id,id,old,{kind:'bag',holder:e.u.id}),/già spostato/);assert.equal(move(e,'equipped',e.u.id,'body'),null);assert(e.g.save());assert(e.g.load());assert.equal(e.g.personEquipment(e.u.id).slots.body.id,id);assert.equal(e.g.gear.filter(i=>i.id===id).length,1);});
test('wrong slot, occupied slot and foreign owner are atomic rejections',()=>{const e=setup(),before=JSON.stringify(e.g.gear);assert.match(move(e,'equipped',e.u.id,'head'),/incompatibile/);assert.match(move(e,'bag',e.g.units[1].id),/accessibile/);assert.equal(JSON.stringify(e.g.gear),before);e.g.gear.push({id:'second-tunic',type:'tunic',location:{kind:'bag',holder:e.u.id}});assert.match(e.g.transferEquipment(e.u.id,'second-tunic',{kind:'bag',holder:e.u.id},{kind:'equipped',holder:e.u.id,slot:'body'}),/occupato/);});
test('bag capacity rejection retains equipped object',()=>{const e=setup();for(let i=0;i<4;i++)e.g.gear.push({id:'bag-'+i,type:'cap',location:{kind:'bag',holder:e.u.id}});assert.match(move(e,'bag'),/esaurito/);assert.equal(e.item.location.kind,'equipped');});
test('storage transfers require living owned reachable local rack',()=>{const e=setup(),b=e.g.buildings.find(b=>b.type==='base');e.u.x=b.x+10;e.u.y=b.y;assert.match(move(e,'storage',b.id),/accessibile/);e.u.x=b.x+1;assert.equal(move(e,'storage',b.id),null);assert.equal(move(e,'bag'),null);b.owner=1;assert.match(move(e,'storage',b.id),/accessibile/);b.owner=0;b.health=0;assert.match(move(e,'storage',b.id),/accessibile/);});
test('full rack does not swallow equipment or modify bulk goods',()=>{const e=setup(),b=e.g.buildings.find(b=>b.type==='base');e.u.x=b.x+1;e.u.y=b.y;for(let i=0;i<8;i++)e.g.gear.push({id:'rack-'+i,type:'cap',location:{kind:'storage',holder:b.id}});assert.match(move(e,'storage',b.id),/esaurito/);assert.equal(e.item.location.kind,'equipped');});
test('resident entry and exit retain same gear owner and ID',()=>{const e=setup(),b=e.run("(()=>{const b=new Building('house',45,45,0,true);game.buildings.push(b);return b})()");assert.equal(e.g.enterResident(e.u,b),true);assert.equal(move(e,'storage',b.id),null);assert.equal(move(e,'equipped',e.u.id,'body'),null);assert(e.g.save());assert(e.g.load());assert.equal(e.g.personEquipment(e.u.id).slots.body.id,e.item.id);});
test('death drops objects once before removal/autosave, pickup needs proximity',()=>{const e=setup(),other=e.g.units[1],id=e.item.id;e.u.health=0;e.g.autosave=21;e.g.update(.05);const item=e.g.gear.find(i=>i.id===id);assert.equal(item.location.kind,'ground');const pos={...item.location};other.x=pos.x+20;other.y=pos.y;assert.match(e.g.transferEquipment(other.id,id,pos,{kind:'bag',holder:other.id}),/accessibile/);other.x=pos.x;assert.equal(e.g.transferEquipment(other.id,id,pos,{kind:'bag',holder:other.id}),null);assert(e.g.save());assert(e.g.load());assert.equal(e.g.gear.filter(i=>i.id===id).length,1);});
test('destroyed storage drops rack contents without duplication',()=>{const e=setup(),b=e.g.buildings.find(b=>b.type==='base');e.u.x=b.x+1;e.u.y=b.y;assert.equal(move(e,'storage',b.id),null);b.health=0;e.g.recoverDeadCargo();e.g.recoverDeadCargo();assert.equal(e.item.location.kind,'ground');assert.equal(e.g.gear.length,5);assert(e.g.save());});
test('old v5 snapshot initializes empty gear without fabricating items or overwriting original',()=>{const e=setup(),d=JSON.parse(JSON.stringify(e.g.snapshot()));delete d.gear;delete d.equipmentRules;const raw=JSON.stringify(d);e.storage.set('terra-italica-save-v5',raw);assert(e.g.load());assert.equal(e.g.gear.length,0);assert.equal(e.storage.get('terra-italica-save-v5'),raw);assert(e.g.save());assert(e.g.load());assert.equal(e.g.gear.length,0);});
test('invalid duplicate IDs, references, slots and capacities reject without changing live world',()=>{for(const mutate of [d=>d.gear.push({...d.gear[0]}),d=>d.gear[0].location.holder='absent',d=>d.gear[0].location.slot='head',d=>d.gear.push({...d.gear[0],id:'different-id'}),d=>delete d.equipmentRules]){const e=setup(),before=e.g.units,d=JSON.parse(JSON.stringify(e.g.snapshot()));mutate(d);e.storage.set('terra-italica-save-v5',JSON.stringify(d));assert.equal(e.g.load(),false);assert.equal(e.g.units,before);}});
console.log(`${count} equipment regressions passed.`);
