const test=require('node:test');const assert=require('node:assert/strict');const make=require('./harness.cjs');
function setup(){const e=make(),g=e.g;g.newGame(321);g.raiders=[];g.animals=[];g.nextRaidDay=1e6;for(const t of g.world.tiles){t.biome='grass';t.z=0;}const pen=e.run("(()=>{const b=new Building('pen',45,45,0,true);game.buildings.push(b);game.ensureLivestock();return b})()");return{e,g,pen};}
function sheep(e,g,pen){const a=e.run("new Animal('sheep',46,45,0)");g.animals.push(a);assert.equal(g.assignAnimalToPen(a,pen),null);return a;}
test('workers alone never create livestock products',()=>{const{g,pen}=setup(),u=g.units[0];u.x=pen.x+1;u.y=pen.y;pen.inventory.items.forage=10;assert.equal(g.assignLivestockWorker(u,pen),null);g.buildingDay(pen);assert.equal(pen.inventory.items.milk||0,0);assert.equal(pen.inventory.items.forage,10);});
test('animals without a named worker consume nothing and produce nothing',()=>{const{e,g,pen}=setup();sheep(e,g,pen);pen.inventory.items.forage=10;g.buildingDay(pen);assert.equal(pen.inventory.items.milk||0,0);assert.equal(pen.inventory.items.forage,10);});
test('owned persistent animals plus worker and local forage produce exact milk',()=>{const{e,g,pen}=setup(),a=sheep(e,g,pen),u=g.units[0];u.x=pen.x+1;u.y=pen.y;pen.inventory.items.forage=3;assert.equal(g.assignLivestockWorker(u,pen),null);g.buildingDay(pen);assert.equal(pen.inventory.items.forage,2);assert.equal(pen.inventory.items.milk,2);assert.equal(JSON.stringify(pen.animalIds),JSON.stringify([a.id]));});
test('pen capacity and single ownership prevent duplicate animal links',()=>{const{e,g,pen}=setup(),other=e.run("(()=>{const b=new Building('pen',48,45,0,true);game.buildings.push(b);game.ensureLivestock();return b})()");const animals=[];for(let i=0;i<7;i++){const a=e.run("new Animal('sheep',46,45,0)");g.animals.push(a);animals.push(a);}for(const a of animals.slice(0,6))assert.equal(g.assignAnimalToPen(a,pen),null);assert.match(g.assignAnimalToPen(animals[6],pen),/pieno/);assert.equal(g.assignAnimalToPen(animals[0],other),null);assert(!pen.animalIds.includes(animals[0].id));assert.equal(JSON.stringify(other.animalIds),JSON.stringify([animals[0].id]));});
test('full local output blocks both production and forage consumption',()=>{const{e,g,pen}=setup(),u=g.units[0];sheep(e,g,pen);u.x=pen.x+1;u.y=pen.y;g.assignLivestockWorker(u,pen);pen.inventory.capacity=1;pen.inventory.items.forage=1;g.buildingDay(pen);assert.equal(pen.inventory.items.forage,1);assert.equal(pen.inventory.items.milk||0,0);});
test('animal IDs, pen link, worker and local products survive reload',()=>{const{e,g,pen}=setup(),u=g.units[0],a=sheep(e,g,pen);u.x=pen.x+1;u.y=pen.y;pen.inventory.items.forage=2;g.assignLivestockWorker(u,pen);g.buildingDay(pen);assert(g.save());assert(g.load());const loadedPen=g.buildings.find(b=>b.id===pen.id),loadedAnimal=g.animals.find(x=>x.id===a.id),loadedWorker=g.units.find(x=>x.id===u.id);assert.equal(loadedAnimal.penId,loadedPen.id);assert.equal(JSON.stringify(loadedPen.animalIds),JSON.stringify([loadedAnimal.id]));assert.equal(JSON.stringify(loadedPen.workers),JSON.stringify([loadedWorker.id]));assert.equal(loadedPen.inventory.items.milk,2);assert.equal(loadedPen.inventory.items.forage,1);});
test('dead or missing animals are pruned and cannot produce',()=>{const{e,g,pen}=setup(),u=g.units[0],a=sheep(e,g,pen);u.x=pen.x+1;u.y=pen.y;pen.inventory.items.forage=2;g.assignLivestockWorker(u,pen);a.health=0;g.ensureLivestock();g.buildingDay(pen);assert.equal(pen.animalIds.length,0);assert.equal(pen.inventory.items.forage,2);assert.equal(pen.inventory.items.milk||0,0);});
