const test=require('node:test'),assert=require('node:assert/strict'),make=require('./harness.cjs');
const setup=()=>{const e=make(),g=e.g,m=e.run(`(()=>{const b=new Building('market',40,40,0,true);game.buildings.push(b);game.ensureMarkets();return b})()`),u=g.units[0];u.x=m.x+1;u.y=m.y;u.path=[];return{...e,g,m,u}};

test('market has persistent ID, local goods, liquidity and stock-sensitive price',()=>{const{g,m}=setup();m.inventory.items.grain=1;const scarce=g.marketPrice(m,'grain','buy');m.inventory.items.grain=40;assert(g.marketPrice(m,'grain','buy')<scarce);assert.equal(typeof m.id,'string');assert.equal(m.money,180)});
test('purchase uses only market stock and trader money, never common-house stock',()=>{const{g,m,u}=setup(),base=g.buildings.find(b=>b.type==='base');m.inventory.items.grain=5;base.inventory.items.grain=99;u.money=100;const r=g.tradeAtMarket({market:m,trader:u,good:'grain',quantity:3,side:'buy',transactionId:'buy-1'});assert(r.ok);assert.equal(m.inventory.items.grain,2);assert.equal(base.inventory.items.grain,99);assert.equal(u.inventory.amount,3);assert.equal(m.money,180+r.total)});
test('availability and trader liquidity are hard constraints',()=>{const{g,m,u}=setup();m.inventory.items.iron=1;u.money=0;assert.equal(g.tradeAtMarket({market:m,trader:u,good:'iron',quantity:1,side:'buy',transactionId:'poor'}).ok,false);u.money=999;assert.equal(g.tradeAtMarket({market:m,trader:u,good:'iron',quantity:2,side:'buy',transactionId:'nostock'}).ok,false);assert.equal(m.inventory.items.iron,1)});
test('sale requires carried local goods and market liquidity/capacity',()=>{const{g,m,u}=setup();u.inventory={type:'barley',amount:4,cap:10};m.money=999;const r=g.tradeAtMarket({market:m,trader:u,good:'barley',quantity:3,side:'sell',transactionId:'sell-1'});assert(r.ok);assert.equal(u.inventory.amount,1);assert.equal(m.inventory.items.barley,3);m.money=0;assert.equal(g.tradeAtMarket({market:m,trader:u,good:'barley',quantity:1,side:'sell',transactionId:'broke'}).ok,false)});
test('same transaction id replays receipt without duplicating money or goods',()=>{const{g,m,u}=setup();m.inventory.items.food=5;u.money=100;const q={market:m,trader:u,good:'food',quantity:2,side:'buy',transactionId:'tap-1'},first=g.tradeAtMarket(q),money=u.money,stock=m.inventory.items.food,second=g.tradeAtMarket(q);assert(first.ok);assert(second.replayed);assert.equal(u.money,money);assert.equal(m.inventory.items.food,stock);assert.equal(u.inventory.amount,2)});
test('market, money, demand and ledger survive save/reload',()=>{const{g,m,u}=setup();m.inventory.items.milk=4;u.money=100;const r=g.tradeAtMarket({market:m,trader:u,good:'milk',quantity:2,side:'buy',transactionId:'persist-1'});assert(r.ok);const money=m.money;assert(g.save());assert(g.load());const loaded=g.buildings.find(b=>b.id===m.id),person=g.units.find(x=>x.id===u.id);assert.equal(loaded.money,money);assert.equal(loaded.inventory.items.milk,2);assert.equal(loaded.tradeLedger[0].id,'persist-1');assert.equal(person.inventory.amount,2)});
