const test=require('node:test'),assert=require('node:assert/strict'),make=require('./harness.cjs');
const setup=()=>{const e=make([],{neutrals:true}),g=e.g;g.ensurePolitics();return{...e,g,s:g.neutralSettlement(1),own:g.buildings.find(b=>b.owner===0&&b.type==='base')}};
test('political values and exactly one compatible relation exist per settlement',()=>{const{g,sandbox}=setup();for(const f of sandbox.TERRA_NEUTRALS.factions){const b=g.neutralSettlement(f.owner).base;assert.equal(b.relationship,'neutral');for(const k of['loyalty','resistance','playerInfluence'])assert(b[k]>=0&&b[k]<=100)}});
test('gift spends only local unreserved player food and changes influence visibly',()=>{const{g,s,own}=setup();own.inventory.items.food=20;const r=g.diplomacyAction(1,'gift','gift-1');assert(r.ok);assert.equal(own.inventory.items.food,15);assert.equal(s.base.playerInfluence,12);assert.equal(s.base.loyalty,54);assert.equal(s.base.resistance,42)});
test('same diplomatic transaction is idempotent',()=>{const{g,s,own}=setup();own.inventory.items.food=20;const first=g.diplomacyAction(1,'gift','same'),food=own.inventory.items.food,influence=s.base.playerInfluence,second=g.diplomacyAction(1,'gift','same');assert(first.ok);assert(second.replayed);assert.equal(own.inventory.items.food,food);assert.equal(s.base.playerInfluence,influence)});
test('shortage raises resistance and can make a settlement hostile',()=>{const{g,s}=setup();s.base.loyalty=25;s.base.resistance=72;s.base.inventory.items.food=0;s.base.inventory.items.bread=0;s.base.inventory.items.barleyBread=0;g.totalDays=30;g.neutralEconomyDay();assert.equal(s.base.relationship,'hostile');assert(s.base.resistance>=75);assert(s.base.loyalty<=22)});
test('friendly and allied relations alter prices while hostility blocks trade',()=>{const{g,s}=setup(),m=s.market,u=g.units.find(x=>x.owner===0);m.inventory.items.iron=20;u.x=m.x+1;u.y=m.y;u.money=999;const neutral=g.marketPrice(m,'iron','buy');s.base.playerInfluence=40;g.ensurePolitics();assert(g.marketPrice(m,'iron','buy')<neutral);s.base.playerInfluence=80;s.base.loyalty=70;s.base.resistance=20;g.ensurePolitics();assert.equal(s.base.relationship,'allied');assert(g.marketPrice(m,'iron','buy')<neutral);s.base.resistance=80;g.ensurePolitics();assert.equal(g.tradeAtMarket({market:m,trader:u,good:'iron',quantity:1,side:'buy',transactionId:'blocked'}).ok,false)});
test('relation transitions preserve every person, owner, store and good',()=>{const{g,s,own}=setup(),ids=s.people.map(u=>u.id),stock=JSON.stringify(s.base.inventory.items),owner=s.base.owner;own.inventory.items.food=50;for(let i=0;i<7;i++)assert(g.diplomacyAction(1,'gift',`g-${i}`).ok);assert.equal(s.base.relationship,'allied');assert.deepEqual(s.people.map(u=>u.id),ids);assert(s.people.every(u=>u.owner===owner));assert.equal(JSON.stringify(s.base.inventory.items),stock);assert.equal(s.base.owner,owner)});
test('politics and ledger survive reload; legacy neutral save gets conservative defaults',()=>{const{g,s,own,storage}=setup();own.inventory.items.food=20;g.diplomacyAction(1,'gift','persist');assert(g.save());assert(g.load());let loaded=g.neutralSettlement(1).base;assert.equal(loaded.playerInfluence,12);assert.equal(loaded.diplomacyLedger[0].id,'persist');const raw=JSON.parse(storage.get('terra-italica-save-v5'));delete raw.politicsRules;for(const b of raw.buildings){delete b.loyalty;delete b.resistance;delete b.playerInfluence;delete b.relationship;delete b.diplomacyLedger;}storage.set('terra-italica-save-v5',JSON.stringify(raw));assert(g.load());loaded=g.neutralSettlement(1).base;assert.equal(loaded.relationship,'neutral');assert.equal(loaded.playerInfluence,0)});
