const {test}=require('node:test');
const assert=require('node:assert/strict');
const make=require('./harness.cjs');
function setup(neutrals=false){const e=make([],{neutrals}),g=e.g;g.newGame(1234);g.raiders=[];g.animals=[];for(const t of g.world.tiles){t.biome='grass';t.z=0;}e.add=(type,x,y,owner=0)=>{const b=e.run(`new Building('${type}',${x},${y},${owner},true)`);g.buildings.push(b);g.ensureSettlement();return b;};e.base=g.buildings.find(b=>b.owner===0&&b.type==='base');e.w=g.communalStores()[0];e.x=Math.floor(e.base.x);e.y=Math.floor(e.base.y);return e;}
test('totem migration preserves quantities and is idempotent; only linked warehouses fund construction',()=>{const e=setup(),{g,w,base}=e;assert.equal(base.inventory.items.food||0,0);assert.equal(w.inventory.items.food,70);g.initializeSettlement();assert.equal(w.inventory.items.food,70);const m=e.add('market',e.x+2,e.y);m.inventory.items.wood=100;g.linkPolicy(w,base).enabled=false;assert.equal(g.canPay({wood:1}),false);g.linkPolicy(w,base).enabled=true;const before=w.inventory.items.wood;assert(g.pay({wood:10}));assert.equal(w.inventory.items.wood,before-10);assert.equal(m.inventory.items.wood,100);});
test('warehouse thresholds and closed links conserve goods',()=>{const e=setup(),{g,w}=e,m=e.add('market',e.x+2,e.y);g.units=[];w.inventory.items={wood:50};const p=g.linkGoodPolicy(w,m,'wood');Object.assign(p,{min:10,keep:30,import:true,export:true});g.settlementTick();assert.equal(w.inventory.items.wood,38);assert.equal(m.inventory.items.wood,12);w.inventory.items.wood=0;g.settlementTick();assert.equal(w.inventory.items.wood,10);assert.equal(m.inventory.items.wood,2);g.linkPolicy(w,m).enabled=false;w.inventory.items.wood=50;g.settlementTick();assert.equal(w.inventory.items.wood,50);});
test('food consumed once across village and artisan assignment; work pauses when unfed',()=>{const e=setup(),{g}=e,m=e.add('market',e.x+2,e.y),f=e.add('sawmill',e.x+3,e.y),u=g.units[0];g.feedPeople();const food=e.w.inventory.items.food;u.x=f.x;u.y=f.y;assert.equal(g.assignProduction(u,f),null);f.inventory.items.wood=10;g.feedPeople();assert.equal(e.w.inventory.items.food,food);g.updateBuilding(f,1);assert(f.batch);g.totalDays=31;const time=f.batch.remaining;g.updateBuilding(f,5);assert.equal(f.batch.remaining,time);f.inventory.items.food=1;g.feedPeople();assert.equal(f.inventory.items.food,0);g.updateBuilding(f,1);assert(f.batch.remaining<time);});
test('autonomous artisans retain identity and bed, produced quota returns exactly once',()=>{const e=setup(),{g,w}=e,m=e.add('market',e.x+2,e.y),f=e.add('sawmill',e.x+3,e.y),h=e.add('house',e.x+2,e.y+2),u=g.units[0];g.enterResident(u,h);m.inventory.items={food:10,wood:20};const count=g.units.length;g.settlementTick();assert.equal(g.units.length,count);assert.equal(u.task.type,'production');assert.equal(u.homeVillageId,h.id);assert.equal(g.villagePeople(h).length,1);u.x=f.x;u.y=f.y;g.updateBuilding(f,1);assert(f.batch);g.updateBuilding(f,10);assert.equal(f.inventory.items.planks,8);assert.equal(f.returnDue.planks,6);g.settlementTick();assert.equal(w.inventory.items.planks,6);assert.equal(m.inventory.items.planks,2);assert.equal(f.returnDue.planks,0);g.settlementTick();assert.equal(w.inventory.items.planks+m.inventory.items.planks,8);});
test('full or disconnected warehouse retains commission goods without loss',()=>{const e=setup(),{g,w,base}=e,m=e.add('market',e.x+2,e.y),f=e.add('sawmill',e.x+3,e.y);f.desiredWorkers=0;f.inventory.items.planks=8;f.returnDue.planks=6;g.linkPolicy(w,base).enabled=false;g.settlementTick();assert.equal(f.inventory.items.planks,6);assert.equal(f.returnDue.planks,6);assert.equal(m.inventory.items.planks,2);});
test('growth requires fed villagers, a market and a stable food surplus',()=>{const e=setup(),{g}=e,m=e.add('market',e.x+2,e.y),h=e.add('house',e.x+3,e.y);for(const u of g.units.slice(0,2))g.enterResident(u,h);assert(g.admissionBlocker(h));m.inventory.items.food=50;g.feedPeople();assert.equal(g.admissionBlocker(h),null);h.birthDays=149;g.buildingDay(h);assert.equal(g.units.length,6);assert.equal(h.residents.length,3);m.inventory.items.food=0;h.birthDays=50;g.buildingDay(h);assert.equal(h.birthDays,0);});
test('physical barter: source pickup, external exchange, return inventory, no duplication',()=>{const e=setup(),{g}=e,a=e.add('market',e.x+2,e.y),b=e.add('market',e.x+5,e.y,1),u=g.units[0];a.inventory.items.wood=10;b.inventory.items.food=10;g.marketPrice=()=>1;const d={source:a,market:b,trader:u,offerGood:'wood',offerQuantity:10,good:'food',quantity:5};assert.equal(g.assignCaravan(d),null);u.x=a.x;u.y=a.y;g.updateCaravan(u,0);assert.equal(a.inventory.items.wood,0);assert.equal(u.inventory.amount,10);u.x=b.x;u.y=b.y;g.updateCaravan(u,0);assert.equal(b.inventory.items.food,5);assert.equal(b.inventory.items.wood,10);assert.equal(u.inventory.type,'food');u.x=a.x;u.y=a.y;g.updateCaravan(u,0);assert.equal(a.inventory.items.food,5);assert.equal(u.inventory.amount,0);assert.equal(u.task,null);});
test('failed barter returns the original cargo; full origin keeps cargo on trader',()=>{const e=setup(),{g}=e,a=e.add('market',e.x+2,e.y),b=e.add('market',e.x+5,e.y,1),u=g.units[0];g.marketPrice=()=>1;a.inventory.items.wood=10;b.inventory.items.food=5;assert.equal(g.assignCaravan({source:a,market:b,trader:u,offerGood:'wood',offerQuantity:10,good:'food',quantity:5}),null);u.x=a.x;u.y=a.y;g.updateCaravan(u,0);b.inventory.items.food=0;u.x=b.x;u.y=b.y;g.updateCaravan(u,0);assert.equal(u.task.traded,false);a.inventory.items.stone=a.inventory.capacity;u.x=a.x;u.y=a.y;g.updateCaravan(u,0);assert.equal(u.inventory.amount,10);a.inventory.items.stone=0;g.updateCaravan(u,0);assert.equal(a.inventory.items.wood,10);});
test('construction reserves and consumes communal resources once',()=>{const e=setup(),{g,w}=e;const before=w.inventory.items.wood;g.placeBuild('farm',e.x+4,e.y+3);const b=g.buildings.find(b=>b.type==='farm');assert(b);assert.equal(w.inventory.items.wood,before-6);assert.equal(b.inventory.items.wood,6);assert(g.consumeSiteMaterials(b));assert.equal(g.consumeSiteMaterials(b),false);assert.equal(w.inventory.items.wood,before-6);});
test('save/load preserves links, food coverage, quotas and barter cargo, including all factions',()=>{const e=setup(true),{g}=e,m=e.add('market',e.x+2,e.y),f=e.add('sawmill',e.x+3,e.y);g.settlementTick();g.linkPolicy(m,f).enabled=false;f.returnDue.planks=6;f.inventory.items.planks=6;assert(g.save(),g.lastSaveError);assert(g.load());const loaded=g.buildings.find(b=>b.id===f.id);assert.equal(loaded.returnDue.planks,6);assert.equal(g.linkOpen(g.buildings.find(b=>b.id===m.id),loaded),false);assert.equal(g.units.filter(u=>u.owner===0).length,5);assert(g.save(),g.lastSaveError);});
test('empty renewable spots can be selected and razed permanently; cargo never regrows',()=>{const e=setup(),{g}=e,r=g.world.resources.find(r=>r.type==='wood');r.amount=0;const u=g.units[0];u.x=r.x+1;u.y=r.y;assert.equal(g.pickEntity({x:r.x,y:r.y}).id,r.id);assert(g.clearResource(r));g.totalDays+=2000;g.resourceRegenerationDay();assert.equal(r.amount,0);assert(r.cleared);const drop=e.run("new ResourceNode('food',20,20,2)");g.world.resources.push(drop);g.ensureResourceRules();assert.equal(drop.renewable,false);});
test('malformed economic settings reject without replacing live state',()=>{for(const corrupt of [b=>b.desiredWorkers=-1,b=>b.returnPercent=200,b=>b.linkSettings={x:{enabled:true,goods:{wood:{min:50,keep:1,import:true,export:true}}}}]){const e=setup(),{g}=e,d=JSON.parse(JSON.stringify(g.snapshot()));corrupt(d.buildings[0]);const before=g.world;e.storage.set('terra-italica-save-v5',JSON.stringify(d));assert.equal(g.load(),false);assert.equal(g.world,before);}});
