const assert=require('node:assert/strict');
const make=require('./harness.cjs');
const SLOT='terra-italica-save-v3';
function setup(){const env=make(),g=env.g;g.newGame(123);g.raiders=[];g.animals=[];g.paused=false;g.nextRaidDay=100000;g.units.forEach(u=>{u.stance='passive';u.x=40.5;u.y=40.5;u.task=null;u.state='idle'});for(const t of g.world.tiles){t.biome='grass';t.z=0;t.nearWater=false;}return env;}
function building(e,type,x,y){return e.run(`(()=>{const b=new Building('${type}',${x},${y},0,true);game.buildings.push(b);game.ensureInventories();return b})()`)}
function tick(g,seconds){for(let t=0;t<seconds;t+=.05)g.update(.05)}
let count=0;
function test(name,fn){fn();count++;console.log('PASS',name)}
test('pause/background: no offline advancement, explicit resume',()=>{const {g}=setup();const days=g.totalDays;g.suspend();tick(g,500);assert.equal(g.totalDays,days);g.resumeFromBackground();assert.equal(g.paused,true);tick(g,100);assert.equal(g.totalDays,days);g.setPaused(false);tick(g,1);assert(g.totalDays>days)});
test('snapshot preserves raiders, RNG, IDs, tasks, cargo and fractional calendar',()=>{const e=setup(),g=e.g;g.spawnRaid();g.units[0].inventory={type:'wood',amount:4,cap:14};g.dayAccumulator=.42;const id=g.raiders[0].id,rng=g.rng.s;g.assignAttack(g.units[1],g.raiders[0]);assert(g.save());assert(g.load());assert.equal(g.raiders[0].id,id);assert.equal(g.units[1].task.target,id);assert.equal(g.rng.s,rng);assert.equal(g.units[0].inventory.amount,4);assert.equal(g.dayAccumulator,.42)});
test('malformed save never replaces live state',()=>{const {g,storage}=setup();g.save();const oldWorld=g.world,unit=g.units[0];storage.set(SLOT,'{"version":3}');assert.equal(g.load(),false);assert.equal(g.world,oldWorld);assert.equal(g.units[0],unit)});
test('quota failure preserves committed save and reports failure',()=>{const {g,sandbox,storage}=setup();g.save();const raw=storage.get(SLOT);sandbox.localStorage.setItem=()=>{throw Object.assign(new Error('Quota'),{name:'QuotaExceededError'})};assert.equal(g.save(true),false);assert.equal(storage.get(SLOT),raw);assert.equal(g.saveFailed,true)});
test('legacy migration retains original and moves stock into central inventory',()=>{const {g,storage}=setup();const d=g.snapshot();delete d.version;d.stock={food:70,wood:55,stone:24,iron:0};for(const b of d.buildings)delete b.inventory;delete d.clock.dayAccumulator;const old=JSON.stringify(d);storage.set('terra-italica-save-v2',old);assert(g.load());assert.equal(g.stock.wood,55);assert(g.save());assert.equal(storage.get('terra-italica-save-v2'),old);assert.equal(JSON.parse(storage.get(SLOT)).version,3)});
test('overlapping reservations cannot double spend; cancel releases source and destination',()=>{const e=setup(),g=e.g,src=building(e,'warehouse',41,40),dst=building(e,'mill',43,40);src.inventory.items.grain=10;dst.inventory.capacity=8;assert.equal(g.assignHaul(g.units[0],src,dst,'grain',true),null);assert.equal(g.units[0].task.amount,8);assert.equal(g.assignHaul(g.units[1],src,dst,'grain',true),null);assert.equal(g.units[1].task.amount,0);assert.equal(g.available(src,'grain'),2);g.cancelTask(g.units[0]);assert.equal(g.available(src,'grain'),10);assert.equal(g.freeSpace(dst),8)});
test('pickup, reload, delivery conserve goods and do not duplicate',()=>{const e=setup(),g=e.g,src=building(e,'warehouse',40,40),dst=building(e,'warehouse',44,40),u=g.units[0];src.inventory.items.grain=10;assert.equal(g.assignHaul(u,src,dst,'grain',false),null);g.updateHaul(u,.05);assert.equal(src.inventory.items.grain,0);assert.equal(u.inventory.amount,10);assert(g.save());assert(g.load());g.setPaused(false);tick(g,8);const saved=g.units.find(x=>x.id===u.id);assert.equal(saved.inventory.amount,0);assert.equal(g.buildings.find(b=>b.id===dst.id).inventory.items.grain,10);tick(g,8);assert.equal(g.buildings.find(b=>b.id===dst.id).inventory.items.grain,10)});
test('cancel after pickup retains cargo; unreachable delivery cannot teleport goods',()=>{const e=setup(),g=e.g,src=building(e,'warehouse',40,40),dst=building(e,'warehouse',44,40),u=g.units[0];src.inventory.items.grain=8;g.assignHaul(u,src,dst,'grain',true);g.updateHaul(u,.05);g.cancelTask(u);assert.equal(u.inventory.amount,8);g.findPath=()=>[];u.task={type:'return',target:dst.id};g.deposit(u,null);assert.equal(u.inventory.amount,8);assert.equal(dst.inventory.items.grain||0,0)});
test('death drops cargo and releases reservations before autosave',()=>{const e=setup(),g=e.g,src=building(e,'warehouse',40,40),dst=building(e,'warehouse',44,40),u=g.units[0];src.inventory.items.grain=8;g.assignHaul(u,src,dst,'grain',true);g.updateHaul(u,.05);u.health=0;g.autosave=21;g.update(.05);assert.equal(g.reserved(dst.id,null,'in'),0);assert.equal(g.world.resources.filter(r=>r.type==='grain').reduce((s,r)=>s+r.amount,0),8);assert(g.load());assert.equal(g.world.resources.filter(r=>r.type==='grain').reduce((s,r)=>s+r.amount,0),8)});
test('grain field keeps entire harvest locally and stops when full',()=>{const e=setup(),g=e.g,farm=building(e,'farm',40,40),u=g.units[0];g.assignFarm(u,farm);u.state='farming';farm.growth=1;g.buildingDay(farm);assert(farm.inventory.items.grain>0);assert.equal(u.inventory.amount,0);const n=farm.inventory.items.grain;farm.inventory.capacity=n;farm.growth=1;g.buildingDay(farm);assert.equal(farm.inventory.items.grain,n);assert.equal(farm.growth,1)});
test('factories require delivered input; batch persists through save and output capacity is reserved',()=>{const e=setup(),g=e.g,mill=building(e,'mill',41,40);tick(g,10);assert.equal(mill.inventory.items.flour||0,0);mill.inventory.items.grain=2;g.updateBuilding(mill,.05);assert.equal(mill.inventory.items.grain,0);assert.equal(mill.batch.amount,2);assert.equal(g.freeSpace(mill),78);assert(g.save());assert(g.load());g.setPaused(false);tick(g,7);const m=g.buildings.find(b=>b.id===mill.id);assert.equal(m.inventory.items.flour,2);assert.equal(m.batch,null)});
test('complete physical chain: field → mill → bakery → center',()=>{const e=setup(),g=e.g,farm=building(e,'farm',40,40),mill=building(e,'mill',43,40),bakery=building(e,'bakery',46,40),base=g.buildings.find(b=>b.type==='base');base.x=49.5;base.y=40.5;g.units[3].x=40.5;g.units[3].y=40.5;g.assignFarm(g.units[3],farm);g.units[3].state='farming';farm.growth=1;g.buildingDay(farm);const harvest=farm.inventory.items.grain;g.cancelTask(g.units[3]);for(const [u,a,b,good]of [[g.units[0],farm,mill,'grain'],[g.units[1],mill,bakery,'flour'],[g.units[2],bakery,base,'bread']])assert.equal(g.assignHaul(u,a,b,good,true),null);tick(g,150);assert(g.stock.bread>=2);const goods=g.buildings.reduce((n,b)=>n+['grain','flour','bread'].reduce((s,k)=>s+(b.inventory.items[k]||0),0)+(b.batch?.amount||0),0)+g.units.reduce((n,u)=>n+(['grain','flour','bread'].includes(u.inventory.type)?u.inventory.amount:0),0);assert.equal(goods,harvest);console.log('  physical delivery:',g.stock.bread,'bread; conserved:',goods)});
test('logistics panel pauses and restores pause state',()=>{const {g,byId}=setup();byId.logisticsBtn.onclick();assert.equal(g.paused,true);assert.equal(byId.logisticsDialog.open,true);byId.closeLogistics.onclick();assert.equal(g.paused,false);g.setPaused(true);byId.logisticsBtn.onclick();byId.closeLogistics.onclick();assert.equal(g.paused,true)});
test('full destination prevents pickup and source factory cannot consume reserved input',()=>{const e=setup(),g=e.g,src=building(e,'mill',40,40),dst=building(e,'warehouse',44,40);src.inventory.items.grain=4;dst.inventory.items.wood=dst.inventory.capacity;g.assignHaul(g.units[0],src,dst,'grain',true);assert.equal(g.units[0].task.phase,'waiting');assert.equal(src.inventory.items.grain,4);dst.inventory.items.wood=0;g.prepareHaul(g.units[0]);g.updateBuilding(src,.05);assert.equal(src.batch,null);assert.equal(src.inventory.items.grain,4)});
test('switching gathered material preserves original cargo',()=>{const e=setup(),g=e.g,u=g.units[0];u.inventory.type='wood';u.inventory.amount=3;const rock=g.world.resources.find(r=>r.type==='stone');g.assignGather(u,rock);assert.equal(u.inventory.type,'wood');assert.equal(u.inventory.amount,3);assert.equal(u.task.type,'return');assert.equal(u.task.after.target,rock.id)});
test('corrupt reservation rejected without mutating game',()=>{const e=setup(),g=e.g,src=building(e,'warehouse',40,40),dst=building(e,'warehouse',44,40);src.inventory.items.grain=4;g.assignHaul(g.units[0],src,dst,'grain',true);g.save();const d=JSON.parse(e.storage.get(SLOT));d.units[0].task.amount=8;e.storage.set(SLOT,JSON.stringify(d));const before=g.world;assert.equal(g.load(),false);assert.equal(g.world,before)});
test('startup restores saved game before autosave and remains paused',()=>{const {g,storage}=setup();g.units[0].inventory={type:'grain',amount:5,cap:15};g.save();const id=g.units[0].id,loaded=make([...storage]);assert.equal(loaded.g.units[0].id,id);assert.equal(loaded.g.units[0].inventory.amount,5);assert.equal(loaded.g.paused,true)});
console.log(`${count} simulation regressions passed.`);
