const assert=require('node:assert/strict');const make=require('./harness.cjs');let count=0;
function test(name,fn){fn();console.log('PASS',name);count++;}
function setup(){const e=make();e.g.newGame(321);return e;}
test('Skill is distinct from Character and bound to the selected ID',()=>{const e=setup(),u=e.g.units[0];e.g.selected=u;e.byId.skillsBtn.onclick();assert(e.byId.skillsDialog.open);assert(!e.byId.characterDialog.open);assert.equal(e.g.skillsPersonId,u.id);assert.match(e.byId.skillsId.textContent,new RegExp(u.id));assert.match(e.byId.skillsList.innerHTML,/Agricoltura/);});
test('person picker changes viewed ID without changing data',()=>{const e=setup(),a=e.g.units[0],b=e.g.units[1],before=JSON.stringify(e.g.units);e.g.openSkills(a.id);e.byId.skillsPeople.value=b.id;e.byId.skillsPeople.onchange();assert.equal(e.g.skillsPersonId,b.id);assert.equal(JSON.stringify(e.g.units),before);});
test('use increases progress and carries overflow across a level',()=>{const e=setup(),u=e.g.units[0];u.xp.wood=19;assert(u.gain('wood',3));assert.equal(u.skills.wood,2);assert.equal(u.xp.wood,2);e.g.openSkills(u.id);assert.match(e.byId.skillsList.innerHTML,/2\/40 XP/);});
test('multiple levels and invalid gains cannot corrupt skills',()=>{const e=setup(),u=e.g.units[0];u.gain('combat',61);assert.equal(u.skills.combat,3);assert.equal(u.xp.combat,1);const before=JSON.stringify([u.skills,u.xp]);assert.equal(u.gain('unknown',5),false);assert.equal(u.gain('combat',-1),false);assert.equal(JSON.stringify([u.skills,u.xp]),before);});
test('progression persists for the same identity',()=>{const e=setup(),u=e.g.units[0];u.gain('construction',27);const id=u.id;assert(e.g.save());u.skills.construction=9;u.xp.construction=0;assert(e.g.load());const restored=e.g.units.find(p=>p.id===id);assert.equal(restored.skills.construction,2);assert.equal(restored.xp.construction,7);});
test('resident view creates no world copy',()=>{const e=setup(),u=e.g.units[0],b=e.run("(()=>{const b=new Building('house',45,45,0,true);game.buildings.push(b);return b})()");e.g.enterResident(u,b);assert(e.g.openSkills(u.id));assert.match(e.byId.skillsIdentity.textContent,/Residente/);assert.equal(e.g.units.filter(p=>p.id===u.id).length,1);assert.equal(u.location.kind,'resident');});
test('close and background preserve pause semantics',()=>{const e=setup(),u=e.g.units[0];e.g.openSkills(u.id);e.byId.closeSkills.onclick();assert.equal(e.g.paused,false);e.g.openSkills(u.id);e.g.suspend();e.g.resumeFromBackground();e.byId.closeSkills.onclick();assert(e.g.paused);});
test('configurable cap is visible and bounded',()=>{const e=setup(),u=e.g.units[0],r=e.sandbox.TERRA_SKILLS;u.skills.farming=r.maxLevel;u.xp.farming=r.maxLevel*r.xpPerLevel-1;u.gain('farming',50);assert.equal(u.skills.farming,r.maxLevel);assert.equal(u.xp.farming,r.maxLevel*r.xpPerLevel);e.g.openSkills(u.id);assert.match(e.byId.skillsList.innerHTML,/massimo/);assert.match(e.byId.skillsRules.textContent,/provvisori configurabili/);});
console.log(`${count} skill regressions passed.`);
