const test=require('node:test'),assert=require('node:assert/strict'),make=require('./harness.cjs');
const setup=()=>{const e=make([],{neutrals:true}),g=e.g;g.ensureWar();return{...e,g}};
test('new game has three persistent hostile camps',()=>{const{g}=setup();assert.equal(g.warCamps.length,3);assert(g.warCamps.every(c=>c.type==='enemy_camp'&&c.health>0&&c.owner===-1));assert.equal(new Set(g.warCamps.map(c=>c.id)).size,3)});
test('raids originate from living camps and stop when every camp is gone',()=>{const{g}=setup(),camp=g.warCamps[0];g.warCamps.slice(1).forEach(c=>c.health=0);g.spawnRaid();assert(g.raiders.length>0);assert(g.raiders.every(r=>r.campId===camp.id));g.raiders=[];camp.health=0;g.spawnRaid();assert.equal(g.raiders.length,0)});
test('victory requires both no living camp and no living raider',()=>{const{g,run}=setup();g.warCamps.forEach(c=>c.health=0);run(`game.raiders.push(new Raider(10,10))`);assert.equal(g.warOutcome(),null);g.raiders[0].health=0;assert.equal(g.warOutcome(),'victory')});
test('resident and mobilized people both prevent false defeat',()=>{const{g}=setup(),own=g.units.filter(u=>u.owner===0),base=g.buildings.find(b=>b.owner===0&&b.type==='base');for(const u of own)u.health=0;own[0].health=100;own[0].location={kind:'resident',settlementId:'test-house'};assert.notEqual(g.warOutcome(),'defeat');own[0].location={kind:'world',settlementId:null};own[0].mobilized=true;assert.notEqual(g.warOutcome(),'defeat');base.health=0;assert.equal(g.warOutcome(),'defeat')});
test('neutral people and deposits cannot prevent player defeat',()=>{const{g}=setup();g.units.filter(u=>u.owner===0).forEach(u=>u.health=0);assert(g.units.some(u=>u.owner>0&&u.health>0));assert(g.buildings.some(b=>b.owner>0&&b.type==='base'&&b.alive));assert.equal(g.warOutcome(),'defeat')});
test('end game records outcome, pauses simulation and saves terminal state',()=>{const{g,storage}=setup();g.warCamps.forEach(c=>c.health=0);g.raiders=[];g.update(.01);assert(g.gameEnded);assert(g.paused);assert.equal(g.gameResult,'victory');const saved=JSON.parse(storage.get('terra-italica-save-v5'));assert.equal(saved.gameEnded,true);assert.equal(saved.gameResult,'victory')});
test('camp damage, raiders and terminal outcome survive reload',()=>{const{g}=setup(),id=g.warCamps[0].id;g.warCamps[0].health=123;g.spawnRaid();assert(g.save());assert(g.load());assert.equal(g.warCamps.find(c=>c.id===id).health,123);assert(g.raiders.length>0);g.warCamps.forEach(c=>c.health=0);g.raiders=[];g.endGame('victory');assert(g.load());assert.equal(g.gameResult,'victory');assert(g.gameEnded)});
